/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateAccountForm: typeof import('./components/CreateAccountForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavigateAuthUser: typeof import('./components/NavigateAuthUser.vue')['default']
    NavigateBar: typeof import('./components/NavigateBar.vue')['default']
    NavigateToShow: typeof import('./components/NavigateToShow.vue')['default']
    PruebaUser: typeof import('./components/PruebaUser.vue')['default']
    RedireccionForm: typeof import('./components/RedireccionForm.vue')['default']
    RegisterRestaurant: typeof import('./components/RegisterRestaurant.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
