/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/buscar-rest': RouteRecordInfo<'/buscar-rest', '/buscar-rest', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/registrar-eventos': RouteRecordInfo<'/registrar-eventos', '/registrar-eventos', Record<never, never>, Record<never, never>>,
    '/registrar-resena': RouteRecordInfo<'/registrar-resena', '/registrar-resena', Record<never, never>, Record<never, never>>,
    '/registrar-rest': RouteRecordInfo<'/registrar-rest', '/registrar-rest', Record<never, never>, Record<never, never>>,
    '/registrar-user': RouteRecordInfo<'/registrar-user', '/registrar-user', Record<never, never>, Record<never, never>>,
    '/ver-eventos': RouteRecordInfo<'/ver-eventos', '/ver-eventos', Record<never, never>, Record<never, never>>,
    '/ver-resenas': RouteRecordInfo<'/ver-resenas', '/ver-resenas', Record<never, never>, Record<never, never>>,
    '/ver-restaurantes': RouteRecordInfo<'/ver-restaurantes', '/ver-restaurantes', Record<never, never>, Record<never, never>>,
  }
}
