# Generated by Django 5.1.1 on 2024-11-12 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='LocalDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(max_length=40)),
                ('calificacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('contacto', models.IntegerField()),
                ('Comentario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.comentariosdb')),
            ],
            options={
                'db_table': 'locales',
            },
        ),
        migrations.CreateModel(
            name='ZonasDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=40)),
                ('local_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.localdb')),
            ],
            options={
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='EventoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=40)),
                ('local_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.localdb')),
                ('zona', models.ManyToManyField(blank=True, to='logica.zonasdb')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
