# Generated by Django 5.1.1 on 2024-11-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localdb',
            name='Comentario_fk',
        ),
        migrations.AddField(
            model_name='comentariosdb',
            name='local_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logica.localdb'),
            preserve_default=False,
        ),
    ]
