# Generated by Django 5.1.1 on 2024-11-20 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_remove_localdb_comentario_fk_comentariosdb_local_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localdb',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
