# Generated by Django 5.1.1 on 2024-11-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0003_localdb_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventodb',
            old_name='calle',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='eventodb',
            old_name='ciudad',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='eventodb',
            name='estado',
        ),
    ]
