# Generated by Django 5.1.1 on 2024-11-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0004_rename_calle_eventodb_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventodb',
            name='local_fk',
        ),
    ]
