# Generated by Django 5.1.1 on 2024-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0005_remove_eventodb_local_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodb',
            name='zona',
            field=models.ManyToManyField(to='logica.zonasdb'),
        ),
    ]
