# Generated by Django 5.1.1 on 2024-11-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0006_alter_eventodb_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonasdb',
            name='local_fk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='logica.localdb'),
        ),
    ]
