# Generated by Django 5.1.1 on 2024-11-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0008_eventodb_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonasdb',
            name='local_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logica.localdb'),
        ),
    ]
