# Generated by Django 5.1.1 on 2024-11-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0009_alter_zonasdb_local_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariosdb',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventodb',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eventodb',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='localdb',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='zonasdb',
            name='calle',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='zonasdb',
            name='ciudad',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='zonasdb',
            name='estado',
            field=models.CharField(max_length=120),
        ),
    ]
