# Generated by Django 5.1.1 on 2024-11-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0010_alter_comentariosdb_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localdb',
            name='calificacion',
        ),
    ]
